version = 3.8.3
runner.dialect = scala3
maxColumn = 140

indent.main = 4
indent.callSite = 4
indent.defnSite = 8

rewrite.trailingCommas.style = multiple
rewrite.rules = [Imports]
rewrite.imports.sort = original
rewrite.imports.expand = true

newlines.afterCurlyLambdaParams = squash
newlines.implicitParamListModifierPrefer = before
newlines.avoidInResultType = true
