name: publish-smarker

on:
  pull_request:
    paths:
      # Trigger only if version changed
      - 'VERSION'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: mvn-central
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: sbt/setup-sbt@v1
      - name: Build and test
        run: sbt test
      - name: Import GPG
        run: echo "${{secrets.PGP_SECRET}}" | base64 -d | gpg --batch --import
      - name: Publish and sign artifacts
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        run: sbt publishSigned
      - name: Upload to Maven Central
        env:
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        run: sbt sonatypeCentralUpload
